# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ffc229884a8885b947b2b465ff40a993435947c2acd60adcfbb52c0f29c85908f7a38561766b26d56774649a24768e5e54c3110ca8542cc9fde2f778f6037d0

test:
  secret_key_base: 95b1b988923f13101fd1ca58d8b2454790c0731e8f5109599908c49a43504748d0fa0762a8323cd1c27b84fda3adf4eec909efeb857d5d7fc9f866ed1a97854a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
